### PR TITLE
Fix #14 - Include group information in rubric export.

### LINKED ISSUE #14: include users groups in export.
It would be good if the users groups could be included in the export - PR incoming.

### PR DESCRIPTION
**Pull request by danmarsden**
@marcusgreen - I tried not to touch too much extra stuff, but I did sneak in a fix for the student idnumber - it wasn't respecting the setting for include/exclude student idnumber in the data - only in the header function. Let me know if you want me to change anything - thanks!

### CODE REVIEW

**Comment by marcusgreen** [comment]
Hi Dan, would it be possible to put this into the settings.php file like I have the studentid field in the new fix/pull I have created.
https://github.com/pauln/moodle-report_componentgrades/pull/16

**Comment by danmarsden** [comment]
sure - Can you please merge in your changes from #16 and I'll rebase mine and add a new setting... I didn't use a setting as I was thinking it was probably enough to check course group mode but I guess some people will want to exlude it? - should I set it as default to "yes" include groups or "no" ?

**Comment by marcusgreen** [comment]
OK, will try to do that tomorrow. I am a bit of a fan of settings, which is why I suggested it. Probably default to yes (or whatever you think would be best for most people)

**Comment by marcusgreen** [comment]
I decided to be bold.... merged.

**Comment by marcusgreen** [comment]
I missed your comment about studentid number this morning, I added my own fix into that thing I just merged, but I had not looked at yours.

**Comment by danmarsden** [comment]
yeah - I saw that - it's the exact same fix :-) - all good - I'll rebase later and fire it through - thanks!

**Comment by marcusgreen** [comment]
Hi Dan, I was thinking of progressing my fixes to the plugins database, possibly over the coming weekend. I can always include your changes after that if you like

**Comment by danmarsden** [comment]
Thanks @marcusgreen - I've just rebased and added an admin setting for this - let me know if you want me to make any further chnages! - thanks.

**Comment by danmarsden** [comment]
I didn't bump the version as I assumed you would do that in the plugins db release, but let me know if you want me to bump it in this commit too.

**Comment by marcusgreen** [comment]
Thanks Dan, I will work on getting it all into an update in the plugins database.

**Comment by marcusgreen** [comment]
I have merged it but it looks like the current master is somewhat broken (almost certainly nothing to do with your changes). Will continue to look into the reasons.

**Comment by marcusgreen** [comment]
Ahh, turns out I didn't understand how it was supposed to work. looking good now I think. Could you pull the current master from here and confirm it does what you expect.

**Comment by danmarsden** [comment]
cool thanks! - looks good to me! :-)

**Pull request merged**
